universe = vanilla
executable = /home/cjoiner/it_anisotropy/stability/submitter/npx4-execs/it_counts_2022_Tier4.sh
log = /home/cjoiner/it_anisotropy/stability/submitter/npx4-logs/it_counts_2022_Tier4.log
output = /home/cjoiner/it_anisotropy/stability/submitter/npx4-out/it_counts_2022_Tier4.out
error = /home/cjoiner/it_anisotropy/stability/submitter/npx4-error/it_counts_2022_Tier4.error
notification = never
getenv = True
queue
